### ISSUE TITLE
Proper syntax highlighting in code blocks

### ISSUE THREAD

**Issue by marrobHD** [SchildiChat/SchildiChat-android#180]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I sent code blocks, but they're shown unformatted and without color. 

**Describe the solution you'd like**
I'd like to have syntax highlighting as integrated in element desktop.

**Describe alternatives you've considered**
:/

**Additional context**
How the formatted block could look:
```yaml
alias: "shutdown server"
fields:
  seconds:
    description: "Seconds until shutdown"
    example: "50"
variables:
  abcd_abcd: abcd
sequence:
  - exec: server.shutdown
    countdown: "{{ seconds }}"
```
